### ISSUE TITLE
Git not found, but git is installed globally with the correct path included.

### ISSUE THREAD

**Issue by kjr247** [orktes/atom-react#106]
Installing “react@undefined” failed.Hide output…
Failed to install react because Git was not found.

The react package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

I tried to:
 close atom
install via: apm install react
which failed with:

npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\KRebstock\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\KRebstock\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\KRebstock\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: Cloning into bare repository 'C:\Users\KRebstock\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! git clone --template=C:\Users\KRebstock\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\KRebstock\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\KRebstock\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\KRebstock\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\KRebstock\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\KRebstock\\.atom\\.apmrc" "install" "C:\\Users\\KREBST~1\\AppData\\Local\\Temp\\d-115919-16636-1omvjt0\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\KRebstock\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by orktes** [comment]
This is most likely related to apm/npm.

On Tuesday, October 20, 2015, Kyle Rebstock <notifications@github.com>
wrote:

> Installing “react@undefined” failed.Hide output…
> Failed to install react because Git was not found.
>
> The react package has module dependencies that cannot be installed without
> Git.
>
> You need to install Git and add it to your path environment variable in
> order to install this package.
>
> You can install Git by downloading, installing, and launching GitHub for
> Windows: https://windows.github.com
>
> Run apm -v after installing Git to see what version has been detected.
>
> I tried to:
> close atom
> install via: apm install react
> which failed with:
>
> npm WARN addRemoteGit Error: Command failed:
> npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:658:15)
> npm WARN addRemoteGit at ChildProcess.emit (events.js:98:17)
> npm WARN addRemoteGit at maybeClose (child_process.js:766:16)
> npm WARN addRemoteGit at Process.ChildProcess._handle.onexit
> (child_process.js:833:5)
> npm WARN addRemoteGit git+
> https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa
> resetting remote
> C:\Users\KRebstock.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f
> because of error: { [Error: Command failed: ] killed: false, code: 1,
> signal: null }
> npm ERR! git clone
> --template=C:\Users\KRebstock.atom.apm_git-remotes_templates --mirror
> https://github.com/millermedeiros/rocambole.git
> C:\Users\KRebstock.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f:
> Cloning into bare repository
> 'C:\Users\KRebstock.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
> npm ERR! git clone
> --template=C:\Users\KRebstock.atom.apm_git-remotes_templates --mirror
> https://github.com/millermedeiros/rocambole.git
> C:\Users\KRebstock.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f:
> fatal: Unable to find remote helper for 'https'
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv
> "C:\Users\KRebstock\AppData\Local\atom\app-1.0.19\resources\app\apm\bin\node.exe"
> "C:\Users\KRebstock\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\bin\npm-cli.js"
> "--globalconfig" "C:\Users\KRebstock\.atom\.apm\.apmrc" "--userconfig"
> "C:\Users\KRebstock\.atom\.apmrc" "install"
> "C:\Users\KREBST~1\AppData\Local\Temp\d-115919-16636-1omvjt0\package.tgz"
> "--target=0.30.7" "--arch=ia32" "--msvs_version=2010"
> npm ERR! node v0.10.40
> npm ERR! npm v2.13.3
> npm ERR! code 128
>
> npm ERR! Command failed: Cloning into bare repository
> 'C:\Users\KRebstock.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
> npm ERR! fatal: Unable to find remote helper for 'https'
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR! https://github.com/npm/npm/issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/106>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by ColCh** [comment]
Hi mate @kjr247. I have same trouble here. I resolved it via installing [Git for Windows](https://git-for-windows.github.io).

Referenced via: [atom-react #106](https://github.com/orktes/atom-react/issues/106)

**Comment by chazzlabs** [comment]
@orktes I'm seeing this issue now when trying to update to version 0.14.0 of the atom-react plugin.  I've not previously had any issues installing earlier versions of the plugin.  Is the Github desktop application my only option in resolving this?  I'd prefer not to install the desktop application if I don't have to.

**Comment by eTorAken** [comment]
I have the same problem as @chazzlabs, I'm running `atom@1.4.0` and `git@2.5.1.windows.1`

**Comment by promethe42** [comment]
Same issue here. Here what I got from `apm -v`:

```
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.5
git 2.6.1.windows.1
visual studio
```

**Comment by jolivr** [comment]
I was able to get it to work by first installing Git for Windows as mentioned earlier [https://git-for-windows.github.io/](https://git-for-windows.github.io/).

Then, instead of opening up a regular command prompt and issuing the `apm install <package>` command, go to your Windows Start menu and open up **Git CMD**. Run the command there and it should work.

**Comment by promethe42** [comment]
I was able to install it after installing Git for Windows too.
But I already had Git installed and Atom knew it.
I don't want to install Git 2 times for every software/plugin I want to use.

**Comment by ColCh** [comment]
@promethe42 try to add GIT to $PATH

**Comment by jgoliver** [comment]
@promethe42 i hear ya on that. i just happened to not already have Git installed. 

The only other suggestion that may help is what @ColCh suggested and add it to PATH. However, I had problems doing that too and I had to use "setx" instead of "set". Maybe that'll work for you as well. Here's a post that helped me understand setx: [http://stackoverflow.com/questions/17240725/setx-doesnt-append-path-to-system-path-variable](http://stackoverflow.com/questions/17240725/setx-doesnt-append-path-to-system-path-variable)

Syntax example is: `setx PATH "%PATH%;C:\Program Files\MySQL\MySQL Server 5.5\bin" /M`

**Comment by promethe42** [comment]
@ColCh git was in my path : I was able to type `git` commands in cmd.exe and atom found it as I mentionned.

**Comment by eTorAken** [comment]
Using `apm install react` with Atom closed fixed the problem for me. Still, that is weird to have to update some packages by forcing the use of `apm`.

**Comment by rijomonr** [comment]
F:\nodejs\angular4\img-search>npm install --save angular/material2-builds angula
r/cdk-builds
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2017-09-27T23_19_04_2
79Z-debug.log

**Comment by ColCh** [comment]
@rijomonr proceed to StackOverflow: https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows

**Comment by abhaykr2013** [comment]
Am a noob also facing the same problem. 
`
Skip to main content
Netlify
abhaykr2013's team
goofy-villani-72ed48
Notifications




























Support










Deploys
Deploy details
Deploy failed
Production: main@HEAD. Today at 10:52 PM

We couldn’t deploy your site. Check out our Build docs for tips on troubleshooting your build, or ask us for debugging advice.

Deploy settings
Retry deploy
Deploy log



10:52:18 PM: Build ready to start
10:52:20 PM: build-image version: d84c79427e8f83c1ba17bcdd7b3fe38059376b68
10:52:20 PM: build-image tag: v3.6.1
10:52:20 PM: buildbot version: 44655717ddf0e7bd7f856f5b1154254de54b1d80
10:52:20 PM: Fetching cached dependencies
10:52:20 PM: Failed to fetch cache, continuing with build
10:52:20 PM: Starting to prepare the repo for build
10:52:20 PM: No cached dependencies found. Cloning fresh repo
10:52:20 PM: git clone https://github.com/abhaykr2013/portfolio
10:52:21 PM: Preparing Git Reference refs/heads/main
10:52:22 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
10:52:23 PM: Starting build script
10:52:23 PM: Installing dependencies
10:52:23 PM: Python version set to 2.7
10:52:24 PM: v12.18.0 is already installed.
10:52:25 PM: Now using node v12.18.0 (npm v6.14.4)
10:52:25 PM: Started restoring cached build plugins
10:52:25 PM: Finished restoring cached build plugins
10:52:25 PM: Attempting ruby version 2.7.1, read from environment
10:52:27 PM: Using ruby version 2.7.1
10:52:28 PM: Using PHP version 5.6
10:52:28 PM: Started restoring cached node modules
10:52:28 PM: Finished restoring cached node modules
10:52:28 PM: Installing NPM modules using NPM version 6.14.4
10:52:32 PM: npm ERR! code E404
10:52:32 PM: npm ERR! 404 Not Found - GET https://abhaykr2013.github.io/portfolio
10:52:32 PM: npm ERR! 404
10:52:32 PM: npm ERR! 404  'homepage@https://abhaykr2013.github.io/portfolio' is not in the npm registry.
10:52:32 PM: npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
10:52:32 PM: npm ERR! 404 It was specified as a dependency of 'repo'
10:52:32 PM: npm ERR! 404
10:52:32 PM: npm ERR! 404 Note that you can also install from a
10:52:32 PM: npm ERR! 404 tarball, folder, http url, or git url.
10:52:32 PM: npm ERR! A complete log of this run can be found in:
10:52:32 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-01-29T17_22_32_336Z-debug.log
10:52:32 PM: Error during NPM install
10:52:32 PM: Build was terminated: Build script returned non-zero exit code: 1
10:52:32 PM: Failing build: Failed to build site
10:52:32 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
10:52:32 PM: Finished processing build request in 12.394628061s
Docs
Pricing
Support
News
Terms
© 2021 Netlify

`
