### ISSUE TITLE
Use spaces for indent (instead of tabs)

### ISSUE THREAD

**Issue by milankarunarathne** [orktes/atom-react#108]
- [ ] should be an option to use spaces for indent, instead of tabs

**Comment by orktes** [comment]
Hi,

You can find it from the editor settings. Or is there something in the
react package it is not affecting.

On Friday, October 30, 2015, Milan Karunarathne <notifications@github.com>
wrote:

>
>    - should be an option to use spaces for indent, instead of tabs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/108>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by rkovacevic** [comment]
I have "Tab type" set to "soft", on Atom 1.2.4, and it's still reformatting to tabs. 

Plugin ver is 0.12.10

**Comment by traviskroberts** [comment]
Is there a reason this issue was closed? I have "Tab type" set to "soft" with a "Tab Length" of 2 in the Atom settings and the package is overwriting this a forcing a tab size of 4. Any way to change that?

**Comment by rsshilli** [comment]
This should definitely not be closed.  I'm having the same issue.
