### ISSUE TITLE
JSX docblock detection not needed since React 0.12

### ISSUE THREAD

**Issue by orktes** [orktes/atom-react#11]
https://github.com/orktes/atom-react/blob/master/index.coffee#L5

I'm not sure if it would be smart to replace it with some other logic (i.e detect require('react')) or just make people manually select it from the menu if their file extension != jsx.

**Comment by MozMorris** [comment]
Manually selecting is unsurprisingly a PITA.

**Comment by orktes** [comment]
Indeed! Any suggestions on patterns that only exist in react files. require('react') only works for commonjs environments. I can though make the pattern/regexp configurable so people can fit it to their needs.

**Comment by janmarek** [comment]
Is it possible to turn JSX automatically on on every .js file?

**Comment by orktes** [comment]
Hi! latest version of atom tries to detect usage of React by detecting require('react') or es6 import statement.
