### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by montogeek** [orktes/atom-react#121]
Hi!

I want to add some RN snippets. How could I proceed?

**Comment by orktes** [comment]
Snippets are located under https://github.com/orktes/atom-react/blob/master/snippets/CoffeeScript%20(JSX).cson.

**Comment by orktes** [comment]
Sorry that was for Coffee :D https://github.com/orktes/atom-react/blob/master/snippets/JavaScript%20(JSX).cson
