### ISSUE TITLE
Switch grammar without needing to save

### ISSUE THREAD

**Issue by antoinerey** [orktes/atom-react#122]
Hi

Is it possible to change the file grammar from '.js' to '.jsx' whenever atom-react detects JSX usage with the regex set in the package settings, without closing / opening the file ?

What it does at the moment :

``` bash
1. Create component.js # The grammar is set to Javascript
2. Add "import React from 'react'"
3. Save the file
4. Close the file
5. Reopen the file # The grammar is set to JSX
```

What I would like to achieve :

``` bash
1. Create component.js # The grammar is set to Javascript
2. Add "import React from 'react'"
3. Save the file # The grammar is set to JSX
```

Any idea please ?

**Comment by orktes** [comment]
You can change from the bottom right corner of the text editor. Doing this automatically on the fly would require periodic check to the file. Should be doable but might be better to implement it as an opt-in setting.

**Comment by orktes** [comment]
ps. files ending with .jsx are automatically detected.
