### ISSUE TITLE
Apostrophe breaks syntax highlighting

### ISSUE THREAD

**Issue by dmnd** [orktes/atom-react#124]
See the closed issue #3

**Comment by orktes** [comment]
Re-opened the old one!

**Comment by reneklacan** [comment]
@orktes thank you

**Comment by kengres** [comment]
it's really still a problem for me, but I'm using **&#39;** now.
![sans titre](https://cloud.githubusercontent.com/assets/14358992/20458278/7eae1cdc-aeb1-11e6-80c2-f9070fd24a28.png)
