### ISSUE TITLE
Syntax highlighting not working properly in atom beta

### ISSUE THREAD

**Issue by hughlomas** [orktes/atom-react#134]
Atom version: `1.4.0-beta3`
"react" Atom Plugin: `0.12.10`
OS: `Windows 8.1 x64`

I apologize if the answer ends up being "well it's an Atom beta version, you'll just have to wait for compatibility". I had to upgrade to the beta to fix a freezing issue with Atom 1.3.

Anyway, notice that the `renderSuggestion` tags are not properly colored..
![image](https://cloud.githubusercontent.com/assets/187210/12177603/f417dc9a-b53a-11e5-919a-bfe19d23f582.png)

I can live with that, but now the incorrect highlighting is causing a major problem when I have an apostrophe in some text.
![image](https://cloud.githubusercontent.com/assets/187210/12177561/cf26d490-b53a-11e5-83dc-a2dd29621527.png)

Is there a quick thing I can do to fix this? 

Thank you

**Comment by silvenon** [comment]
```jsx
<p><b>{"You're only a few minutes..."}
```

I suggest always doing this to avoid other confusing stuff like highlighted keywords.

**Comment by hughlomas** [comment]
@silvenon Works well, thanks!

**Comment by rylanc** [comment]
This is still broken in the stable 1.4 release. It looks like JSX tags (elements) aren't being properly marked with the `tag` selector (among other things).

**Comment by luisrudge** [comment]
Yep. It's broken with the new atom version.

![image](https://cloud.githubusercontent.com/assets/941075/12333517/bc361b2e-badb-11e5-9dba-e77746195527.png)

**Comment by rylanc** [comment]
After further investigation, it looks like this is broken inside the `meta.function-call.js` and `meta.method-call.js` scopes (most likely due to this commit: https://github.com/atom/language-javascript/commit/0b4affd7d1f4039827e898931cad632a8d25a535). I'm guessing that the use of `$self` in the `#arguments` rule includes only the `source.js` scope and excludes any JSX rules. I'm not sure how we'd work around that rule. @orktes Any ideas?

**Comment by orktes** [comment]
I'll take a look tomorrow.

On Thursday, January 14, 2016, Rylan Collins <notifications@github.com>
wrote:

> After further investigation, it looks like this is broken inside the
> meta.function-call.js and meta.method-call.js scopes (most likely due to
> this commit: atom/language-javascript@0b4affd
> <https://github.com/atom/language-javascript/commit/0b4affd7d1f4039827e898931cad632a8d25a535>).
> I'm guessing that the use of $self in the #arguments rule includes only
> the source.js scope and excludes any JSX rules. I'm not sure how we'd
> work around that rule. @orktes <https://github.com/orktes> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/134#issuecomment-171736582>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by orktes** [comment]
Took a stap at it https://github.com/orktes/atom-react/commit/89f26dba337b971ae104022f50054c3383e38414 . Not elegant but seemed to achieve what we are after.

**Comment by orktes** [comment]
releasing new minor

**Comment by orktes** [comment]
react@v0.14.0 published.

**Comment by luisrudge** [comment]
looks like it's working for me. thanks!

**Comment by orktes** [comment]
Nice to hear! Waiting for @rylanc to confirm and closing after that!

**Comment by rylanc** [comment]
Works for me too. Thanks for tackling!

**Comment by hughlomas** [comment]
0.14.0 works for me also, thank you

**Comment by orktes** [comment]
Nice to hear! Closing...
