### ISSUE TITLE
Add semicolon to end of snippets `pt6` and `dp`

### ISSUE THREAD

**Issue by IanVS** [orktes/atom-react#135]
Class static properties require a trailing semicolon, and Babel is now throwing compilation errors if it doesn't find them (see https://phabricator.babeljs.io/T6873).  

The snippets currently generate:

```js
// dp - >
static defaultProps = {
    
}

// pt6 ->
static propTypes = {
    : React.PropTypes.string
}
```

Both of these will cause recent versions of Babel to crash.  I'm happy to submit a PR if you agree.

**Comment by orktes** [comment]
Fine by me! Thanks!

On Thursday, 7 January 2016, Ian VanSchooten <notifications@github.com>
wrote:

> Class static properties require a trailing semicolon, and Babel is now
> throwing compilation errors if it doesn't find them (see
> https://phabricator.babeljs.io/T6873).
>
> The snippets currently generate:
>
> // dp - >static defaultProps = {
>
> }
> // pt6 ->static propTypes = {
>     : React.PropTypes.string
> }
>
> Both of these will cause recent versions of Babel to crash. I'm happy to
> submit a PR if you agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/135>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by jeffshaver** [comment]
The babel thing will likely get changed. Based on the conversations in jeffmo/es-class-fields-and-static-properties#26. I don't know that it would be worth changing

**Comment by IanVS** [comment]
@orktes What do you think?  Worth holding off on, or harmless addition either way?  I can throw a PR your way today if you still want one.

**Comment by jeffshaver** [comment]
@IanVS I think that depends on whether people use semi-colons or not

**Comment by orktes** [comment]
Harmless to add if currently causing issues for people.
