### ISSUE TITLE
trying to install in Atom and i get this...

### ISSUE THREAD

**Issue by rchrdnsh** [orktes/atom-react#136]
npm WARN addRemoteGit git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote /Users/richardnash/.atom/.apm/_git-remotes/https-github-com-millermedeiros-rocambole-git-fa28ae6f because of error: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)
npm ERR! git clone --template=/Users/richardnash/.atom/.apm/_git-remotes/_templates --mirror https://github.com/millermedeiros/rocambole.git /Users/richardnash/.atom/.apm/_git-remotes/https-github-com-millermedeiros-rocambole-git-fa28ae6f: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Code/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Code/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/richardnash/.atom/.apm/.apmrc" "--userconfig" "/Users/richardnash/.atom/.apmrc" "install" "/private/var/folders/8c/l7jbmd914r18_xvlwd9ctm2m0000gn/T/d-116014-17376-1dzq91g/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 1

npm ERR! Command failed: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/8c/l7jbmd914r18_xvlwd9ctm2m0000gn/T/apm-install-dir-116014-17376-z28w9i/npm-debug.log

**Comment by orktes** [comment]
Seems to be a problem with your xcode.
