### ISSUE TITLE
could you add a detailed CHANGELOG.md, please?

### ISSUE THREAD

**Issue by faddah** [orktes/atom-react#137]
could you please add a detailed CHANGELOG.md to this project so we can easily see what has changed/been fixed in each release? i tried looking at your "releases" section here on this github repository but that contains no detail either. thanx.

best,

—  faddah
      portland, oregon, u.s.a.

**Comment by orktes** [comment]
Hi!

There is a changelog in the Readme.md. Will continue update that every time
there is a release.

On Friday, 15 January 2016, Faddah Wolf <notifications@github.com> wrote:

> could you please add a detailed CHANGELOGmd to this project so we can
> easily see what has changed/been fixed in each release? i tried looking at
> your "releases" section here on this github repository but that contains no
> detail either thanx
>
> best,
>
> — faddah
> portland, oregon, usa
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/137>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari
