### ISSUE TITLE
May i know the logic for detecting react code in .js file

### ISSUE THREAD

**Issue by shangsunset** [orktes/atom-react#143]
not a issue here. I like this package a lot as it can detect react code in .js file and add jsx syntax support. so whats the logic for identifying between a react file and a js file? i tried look through the repo, but i really dont understand coffeescript.  thanks.

**Comment by orktes** [comment]
Hi! Plugin currently auto-selects JSX syntax based on the extension name and this regex 

`/((require\\([\'"]react(?:(-native|\\/addons))?[\'"]\\)))|(import\\s+[\\w{},\\s]+\\s+from\\s+[\'"]react(?:(-native|\\/addons))?[\'"])/`

i.e it checks if react or react native is required or imported. You can also force JSX on all .js files from the plugin settings.
