### ISSUE TITLE
Syntax highlighting issue with Atom 1.6

### ISSUE THREAD

**Issue by armed** [orktes/atom-react#148]
Tags is not highlighted when JSX inside parentheses:
<img width="428" alt="screen shot 2016-03-18 at 4 55 28 pm" src="https://cloud.githubusercontent.com/assets/223060/13875863/917909b0-ed2a-11e5-8ce1-22fc3b521c32.png">

But highlights if without parentheses:
<img width="420" alt="screen shot 2016-03-18 at 5 00 17 pm" src="https://cloud.githubusercontent.com/assets/223060/13875922/ecea577c-ed2a-11e5-90f8-d333b02ce941.png">

**Comment by sompylasar** [comment]
The issue appears in `0.14.1` and does not appear in `0.14.0`.

**Comment by sompylasar** [comment]
[This commit](https://github.com/orktes/atom-react/commit/c267e8e376ed5832d488203f9c6cc102a4583279), besides [the README change](https://github.com/orktes/atom-react/commit/e3c53e811be37d676ee3d395eb15aea5e313859e), is the only change between `0.14.0` and `0.14.1`.

**Comment by DerNivel** [comment]
I can add that the auto closing is not working anymore since Atom 1.6

**Comment by sompylasar** [comment]
A duct tape fix here: #149 
Either TextMate grammars are crap in terms of describing nested language constructs, or grammar developers can't grasp the concepts that enable doing it properly.

**Comment by orktes** [comment]
Hi! This should be fixed in v0.14.2.

**Comment by orktes** [comment]
Closing for now! Feel free to reopen if issues persists.

**Comment by sompylasar** [comment]
@orktes thank you for the more generic fix, which [is here](https://github.com/orktes/atom-react/commit/4a600c83f44cedfcb82840168b1a0d81b89f85f2] in case someone is interested (referencing an issue from a commit really helps).

I can't verify the fix because of a funny bug: I've accidentally installed the `facebook/react` library instead of this package via `apm install react@0.14.2`. And I'm still struggling to get rid of it to no avail, it got cached somewhere. For the future, you should really consider changing the published name to something like `atom-react` in the Atom Package Directory.
<img width="777" src="https://cloud.githubusercontent.com/assets/498274/13905398/74aef474-eecf-11e5-9fe3-70e6b0f9690b.png">

**Comment by orktes** [comment]
True! normally I try to remember do that but only noticed the existence of this issue after pushing. Nowadays it seems to be possible to rename packages in a way that request to the old package get redirected to the new one (upgrades etc.). So not a bad idea! I'll look into it.

**Comment by sompylasar** [comment]
@orktes the wrong `react` got cached in `~/.atom/.apm`, resolved after removing that directory.

**Comment by ilyapalkin** [comment]
@sompylasar @orktes Highlighting doesn't work for `react@0.14.2` and `Atom 1.6.0`:
- JSX file is considered as `Plain Text`

Highlighting is broken for `react@0.14.1`
- JSX file is considered as `JavaScript (JSX)`

It works for `react@0.14.0`
- JSX file is considered as `JavaScript (JSX)`

**Comment by silvenon** [comment]
@ilyapalkin Atom sometimes saves the grammar you previously set for that file (i.e. what the broken `react@0.14.1` set for you). All my new JSX files are loaded with the proper grammar in v0.14.2.

**Comment by ilyapalkin** [comment]
@silvenon in version `0.14.1` it sets `JavaScript (JSX)` and higlighting looks similar to https://github.com/orktes/atom-react/issues/148#issue-141835975:

![image](https://cloud.githubusercontent.com/assets/640738/13948292/8c9e8ce2-f01f-11e5-877a-a0b96377c965.png)

When I install `0.14.2` there is no `JavaScript (JSX)` grammar at all.

**Comment by silvenon** [comment]
I have no idea why this would happen, have you tried reinstalling the package?

**Comment by xwinus** [comment]
@silvenon I have the same issue with `0.14.2`, reinstalling does not help. With `0.14.2`, I can't even select the _Javascript (JSX)_ mode (not available in the modes list). When I downgrade to `0.14.0` or `0.14.1`, the _Javascript (JSX)_ mode is available, though the syntax highlighting is broken exactly same as @ilyapalkin showed on screenshot.

Tested on Atom 1.6.0, OS X 10.11.3

**Comment by sompylasar** [comment]
This is probably the same issue I encountered. Try removing `~/.atom/.apm` and then do a fresh install via GUI.

**Comment by xwinus** [comment]
@sompylasar you're right, thanks, cleaning `~/.atom/.apm/react` was sufficient

**Comment by ilyapalkin** [comment]
> cleaning `~/.atom/.apm/react` was sufficient and solved the issue for me

+1

**Comment by enriquecaballero** [comment]
Some weird stuff is happening again.
<img width="380" alt="screen shot 2016-04-08 at 12 24 07 am" src="https://cloud.githubusercontent.com/assets/7918284/14374196/d419ff8a-fd20-11e5-9088-cb6fe50bd518.png">
Not sure if the `import` statements along with the class definition should look like that.
