### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by brukh** [orktes/atom-react#152]
After upgrading to version 0.14.2 the plugin has stopped working for me. I was wondering if this has happened to anyone else? Also not seeing any issues within console. I am running on the latest version of Atom at this time (1.6.0). 

Reverted plugin version back to 0.14.0 for the time being. Any help is appreciated!

**Comment by Gmousse** [comment]
+1. Same issue than brukh.

**Comment by voxpelli** [comment]
One of the major differences I see between version `0.14.0` and `0.14.2` is that the description of the plugin + the owner of the plugin matches this repo at version `0.14.0`, but at version `0.14.2` it's instead Facebook that's the owner and the description is just a generic description of React.

Has this module somehow mistakenly got replaced with React itself or something in version `0.14.2`?

**Comment by orktes** [comment]
Hi! I think something was changed in apm in the latest version of atom and
now it might prefer npm over apm packages with the same name. I'll rename
the plugin tomorrow just in case this is true.

On Sunday, 27 March 2016, Pelle Wessman <notifications@github.com> wrote:

> One of the major differences I see between version 0.14.0 and 0.14.2 is
> that the description of the plugin + the owner of the plugin matches this
> repo at version 0.14.0, but at version 0.14.2 it's instead Facebook
> that's the owner and the description is just a generic description of React.
>
> Has this module somehow mistakenly got replaced with React itself or
> something in version 0.14.2?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/152#issuecomment-202126019>
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by brukh** [comment]
Thanks @orktes - really appreciate it!

Until the issue is resolved I found a workaround.

1. Navigate to your packages directory: ```~/.atom/packages/```
2. Clone the repo: ```git clone https://github.com/orktes/atom-react```
3. Install dependencies: ```apm install```

Restart Atom and it should work. If not launch atom from the command line using ```atom```

Let me know if anyone has questions :+1:

**Comment by orktes** [comment]
Apparently this has been tagged as a bug in APM https://github.com/atom/apm/issues/529. Little bit hesitant in adding a random prefix (even atom-) into the package name if they are able to get this fixed to the soon. I'll try to get more info on the issue.

**Comment by orktes** [comment]
I'll see if releasing a new minor helps with the issue.

**Comment by muuki88** [comment]
I think this is also related to the broken installation: #151 

Installing `0.15.0` fixed all my issues.

**Comment by brukh** [comment]
Updated Atom to `1.6.1` and installed the `v0.15.0` fixed the issues. Thanks for the help @orktes
