### ISSUE TITLE
Code colouring breaks on 'this' string inside element

### ISSUE THREAD

**Issue by gersomvg** [orktes/atom-react#157]
'This' is being mistaken for a reference, while it is just plain text inside an JSX/HTML element.
<img width="567" alt="screen shot 2016-04-10 at 12 51 02" src="https://cloud.githubusercontent.com/assets/8234283/14409686/f239e25e-ff1a-11e5-945e-a0940ca2a7f8.png">

**Comment by TimoSta** [comment]
Same for logical operators. `!` and `&&` are interpreted as operators, not text inside JSX:

![image](https://cloud.githubusercontent.com/assets/5621996/19529343/72d3a638-95fd-11e6-80b9-a36568ad7d09.png)

**Comment by mrbinky3000** [comment]
It seems that all reserved words in JSX text nodes are highlighted when they shouldn't be.
![screen shot 2017-02-21 at 1 37 52 pm](https://cloud.githubusercontent.com/assets/161068/23179180/ffff6642-f83a-11e6-9ae1-7f9845f852ac.png)
