### ISSUE TITLE
JSX indentation breaks upon paste

### ISSUE THREAD

**Issue by dmnd** [orktes/atom-react#16]
![](http://i.gyazo.com/373737a7bb91f80579805bad0cdf9f4c.gif)

In this gif I have the grammar set to Javascript (JSX). I select all text, copy, then paste. I expect it to be a noop, but instead the indentation of the JSX section is stripped.

I'm using Atom 0.165.0 and have "Auto Indent On Paste" enabled.

**Comment by orktes** [comment]
Just got back from abroad and had time to look back in to this. I ended up expanding the indentation functionality in atom to support JSX by monkey patching some of the Language Mode functions at runtime. "Ugly hack" tm but should do the trick for now.  New version published. Closing for now.

**Comment by dmnd** [comment]
Thanks for all your effort!
