### ISSUE TITLE
Option to disable snippets

### ISSUE THREAD

**Issue by jiayihu** [orktes/atom-react#165]
Is there a way to disable snippets? I prefer using my own custom snippets but the ones of this package are listed before mine, forcing me to use arrow keys to select them.

**Comment by LeoBakerHytch** [comment]
Came here to ask exactly this — I very much second the request. Sadly there’s no way to disable snippets globally either (see atom/snippets#55).

**Comment by stevenla** [comment]
Would be great if we can disable only the ES5 snippets

**Comment by jiayihu** [comment]
For the time being I replaced the package with [language-babel](https://atom.io/packages/language-babel) which offers similar features with even some extras and have no snippets.

**Comment by willdady** [comment]
I too have switched to language-babel for this reason. Snippets are quite a subjective thing. Personally I think the snippets should be removed from this package entirely and moved to their own separate package. Or even just turned into a gist which people can copy-paste into their own snippets file and adjust accordingly.

**Comment by Lakston** [comment]
I agree that the snippets should at least have the option to be disabled, I created my own and would love to be able to disable or remove the ones in this package.

I will also replace this package with language-babel until this is addressed.

**Comment by RyanMitchellWilson** [comment]
I would really like if you could disable snippets for this as well.

**Comment by eemeli** [comment]
Because of this issue, I also switched to language-babel.
