### ISSUE TITLE
Auto-generated closing tags do not disappear on undo

### ISSUE THREAD

**Issue by zdhickman** [orktes/atom-react#172]
To reproduce:
1. Start editing a .jsx file
2. Type an opening html tag (e.g. `<div>`). The closing `</div>` tag will be automatically generated.
3. Press undo. The `<div>` tag will be removed, but the closing `</div>` tag will remain

**Comment by wismer** [comment]
can confirm

**Comment by mattfysh** [comment]
this one got me too.. thankfully the failure to compile caught it ;)
