### ISSUE TITLE
Auto Close not working

### ISSUE THREAD

**Issue by levrik** [orktes/atom-react#179]
The auto close feature does not work anymore on Atom 1.9.0-beta.0

Same with the syntax highlighting: #177

**Comment by mywentu** [comment]
me to

**Comment by danludwig** [comment]
My atom auto updated to 1.9.1 and several features are not working any more -- auto close new component element, and syntax highlighting in odd places. Will be looking for a way to roll back atom to 1.8.

**Comment by whiver** [comment]
The same for me, I am also using CJSX, and auto-close does not work in Atom 1.9.4.

**Comment by danludwig** [comment]
I uninstalled ATOM 1.9.1, reinstalled ATOM 1.8, and the package works again.

**Comment by orktes** [comment]
Should be fixed https://github.com/orktes/atom-react/issues/188

**Comment by wangbourne** [comment]
+1
