### ISSUE TITLE
Syntax highlighting ES6 methods

### ISSUE THREAD

**Issue by jsg2021** [orktes/atom-react#18]
:) It would super cool to have ES6 featuers highlighted.

```
var foo = {
	render() { // <-- the word render isn't highlighted
		return "";
	}
};
```

Here's a similar sublime issue: https://github.com/reactjs/sublime-react/pull/28

**Comment by gaearon** [comment]
+1.

https://github.com/6to5/6to5-sublime does that.

**Comment by Erid** [comment]
+1

**Comment by nelix** [comment]
+1

**Comment by frederickfogerty** [comment]
+1

**Comment by roman01la** [comment]
+1

**Comment by zhangsoledad** [comment]
+1

**Comment by gyzerok** [comment]
+1

**Comment by orktes** [comment]
Hi! After some thinking I decided that this should be implemented in https://github.com/atom/language-javascript . Seems that @gyzerok already added an issue. It can be tracked here https://github.com/atom/language-javascript/issues/115 .

**Comment by jsg2021** [comment]
awesome :)

**Comment by AMalininHere** [comment]
You can just use my active supported repo https://github.com/AMalininHere/language-javascript-better as JavaScript highlighter:)

**Comment by orktes** [comment]
That is true. Atom-react is build in a way that it extends the
enabled .source.js grammar.

On Wednesday, March 25, 2015, Alexey Malinin <notifications@github.com>
wrote:

> You can just use my active supported repo
> https://github.com/AMalininHere/language-javascript-better as JavaScript
> highlighter:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/18#issuecomment-86210800>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by AMalininHere** [comment]
I think that you can close this issue.
https://github.com/atom/language-javascript/pull/134

**Comment by jsg2021** [comment]
Thanks!
