### ISSUE TITLE
HTML highlighting doesn't work when wrapped in brackets

### ISSUE THREAD

**Issue by pthorsson** [orktes/atom-react#182]
I noticed I lost the highlighting on the HTML returned by my render function. One common factor I found was that the highlighting breaks when the is wrapped in brackets, on some level.

![react-highlight](https://cloud.githubusercontent.com/assets/1196744/17333787/0d516266-58d4-11e6-9221-37bad62c673a.jpg)

Plain example of what I mean.
![react-highlight2](https://cloud.githubusercontent.com/assets/1196744/17333794/1519e7ac-58d4-11e6-8101-d4ff0bb79f83.jpg)

Atom 1.9.0
atom-react 0.15.0

**Comment by amurp** [comment]
Confirmed. Syntax highlighting and autocomplete have stopped working for me.

<img width="578" alt="screen shot 2016-08-02 at 12 00 26 pm" src="https://cloud.githubusercontent.com/assets/6566097/17335708/e6e2c3c0-58a8-11e6-8b46-d24b51c16e41.png">

Atom 1.9.0
atom-react 0.15.0

**Comment by renderf0x** [comment]
I see this too. I think this may have broken as of some of Atom's latest 1.9.1 release, as it was working up till today for me.

**Comment by preco21** [comment]
Related: #177

**Comment by fpaeslima** [comment]
@renderf0x I think you're right.

I tried with Atom 1.8.0 and it is working like a charm.
![reactsyntax](https://cloud.githubusercontent.com/assets/12243928/17375156/3e4e8be8-5986-11e6-9113-8d965b5a924a.png)

Atom: **1.9.0**
Atom-React: **0.15.0**
System: **Ubuntu64 14.04 LTS**

**Comment by orktes** [comment]
Should be fixed https://github.com/orktes/atom-react/issues/188

**Comment by renderf0x** [comment]
Confirmed on Atom 1.9.6 with the new v0.16.0 update. Thanks!!
