### ISSUE TITLE
Hightlighting sytax problems

### ISSUE THREAD

**Issue by cristian-sima** [orktes/atom-react#183]
![image](https://cloud.githubusercontent.com/assets/12199042/17336745/36b9d386-58e8-11e6-935e-a016b28b1f85.png)

![image](https://cloud.githubusercontent.com/assets/12199042/17336764/505ad150-58e8-11e6-82a0-7651f226bb6d.png)

**Comment by orktes** [comment]
Hi! Will check asap. Seems that atom:s javascript highlighting has changed once again :)

**Comment by orktes** [comment]
should be fixed https://github.com/orktes/atom-react/issues/188
