### ISSUE TITLE
react highlighting and autocomplete not working

### ISSUE THREAD

**Issue by pillowface** [orktes/atom-react#184]
hi yesterday it works but now it doesn't work. Why is that? Can you help me fix it

**Comment by MarcusHurney** [comment]
I'm experiencing the same problem, you aren't alone!

**Comment by mauriciord** [comment]
SAme problem here

**Comment by MarcusHurney** [comment]
I installed the package called language-babel. That works perfectly fine. Another solution is to use this package https://atom.io/packages/language-javascript-jsx. Both **language-babel** and **language-javascript-jsx** will solve this issue until the react package is fixed. Make sure you just use one of these, disable the others.

**Comment by mauriciord** [comment]
I tried that, but not autocompleting yet.

Atenciosamente,
Maurício R. Duarte.

2016-08-04 20:52 GMT-03:00 Marcus Hurney <notifications@github.com>:

**Comment by pillowface** [comment]
I recomend using language-babel https://atom.io/packages/language-babel
It has similiraties to react package since it has autocomplete and highlighting.  The othe package doesn't have autocomplete.

**Comment by MarcusHurney** [comment]
I agree, not having autocomplete is a big disadvantage of the jsx language
package.

**Comment by orktes** [comment]
Should be fixed https://github.com/orktes/atom-react/issues/188
