### ISSUE TITLE
JSX syntax highlighting mysteriously stopped working today

### ISSUE THREAD

**Issue by MarcusHurney** [orktes/atom-react#185]
All the of syntax highlighting for jsx files is no longer working. I tried uninstalling and then reinstalling the package and I also tried uninstalling Atom and then reinstalling it. No of these attempts solved the issue. Everything is up to date as well.

**Comment by eonblue4309** [comment]
What version of atom are you running? I noticed this too after updating to 1.9.1 or 1.9.2 (OSX if it matters)

**Comment by ChunkyBeats** [comment]
Same issue here, 1.9.2 OSX.

**Comment by darrylmack** [comment]
Having the same issue. What's the last know good version of Atom that works?

**Comment by darrylmack** [comment]
So in Atom 1.8 React syntax highlighting works - https://github.com/atom/atom/releases/tag/v1.8.0

**Comment by andersryanc** [comment]
+1 I'm using 1.9.2... just started happening yesterday for me. My guess would be that it worked in 1.9.1 but I can't confirm that.

**Comment by andersryanc** [comment]
I did however install the [language-babel](https://atom.io/packages/language-babel) plugin after this happened and it appears to highlight everything properly in 1.9.2... but it also shows a notice to not have both plugins active at the same time...

**Comment by MarcusHurney** [comment]
I took @andersryanc 's advice and installed language-babel. That works perfectly fine. Another solution is to use a package called [https://atom.io/packages/language-javascript-jsx](language-javascript-jsx). Bother language-babel and language-javascript-jsx will solve this issue until the react package is fixed.

**Comment by GVanderLugt** [comment]
I started having the same issue today. @andersryanc 's advice worked for me.

**Comment by mbeaudru** [comment]
Same here, syntax highlighting broken and language-babel solved it :+1:

**Comment by orktes** [comment]
Should be fixed https://github.com/orktes/atom-react/issues/188
