### ISSUE TITLE
single quote can't be escaped

### ISSUE THREAD

**Issue by newswim** [orktes/atom-react#186]
Hello - I did a fresh install of Atom-React. This could possibly be coming from another package, but here's what I'm seeing:

![Single Quote Bug](http://s32.postimg.org/j4dq40x2t/react_atom_single_quote_bug.png)

**Comment by aihornmac** [comment]
+1

**Comment by orktes** [comment]
Duplicate of https://github.com/orktes/atom-react/issues/3
