### ISSUE TITLE
Pretty much nothing works with atom 1.9.2 (OSX)

### ISSUE THREAD

**Issue by RyanMitchellWilson** [orktes/atom-react#188]
Updated my atom to 1.9.2 and then nothing was working correctly. It stopped autocompleting my JSX, stopped suggesting things and stopped highlighting correctly. Installed language-babel for now, and that is working for the most part in the mean time.

**Comment by rkdavidson** [comment]
+1

**Comment by simonmclean** [comment]
Same issue on Windows

**Comment by Ephasme** [comment]
Same for me... :(

**Comment by dinomujki** [comment]
+!

**Comment by orktes** [comment]
Version v0.16.0 has now been published. Should fix issues that manifested after updating from atom 1.8. Thanks for reporting and your patience. Reopen if you still face problems.
