### ISSUE TITLE
Cannot install the react@0.8.1 package

### ISSUE THREAD

**Issue by morukutsu** [orktes/atom-react#19]
Hello,

I'm trying to install the React package from the builtin Atom package manager but it doesn't work.
It seems to hang on the oniguruma@3.0.5 dependency install. I joined the full log below.
I'm using Atom 0.152.0 on Windows. I also tried on a different computer but I get the same issue.

Thanks in advance,
Uldéric

Log:
oniguruma@3.0.5 install D:\TEMP\apm-install-dir-115015-6656-15qzczw\node_modules\react\node_modules\oniguruma
node-gyp rebuild

D:\TEMP\apm-install-dir-115015-6656-15qzczw\node_modules\react\node_modules\oniguruma>node "d:\atom-windows\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/oniguruma
npm http GET https://registry.npmjs.org/jstransform
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/oniguruma
npm http 304 https://registry.npmjs.org/jstransform
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/esprima-fb
npm http GET https://registry.npmjs.org/base62/0.1.1
npm http GET https://registry.npmjs.org/source-map/0.1.31
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/esprima-fb
npm http GET https://registry.npmjs.org/nan/1.2.0
npm http 304 https://registry.npmjs.org/source-map/0.1.31
npm http 304 https://registry.npmjs.org/base62/0.1.1
npm http 200 https://registry.npmjs.org/nan/1.2.0
npm http GET https://registry.npmjs.org/nan/-/nan-1.2.0.tgz
npm http GET https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/nan/-/nan-1.2.0.tgz
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
gypnpm ERR! oniguruma@3.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@3.0.5 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\atom-windows\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "d:\\atom-windows\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "d:\\atom-windows\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Uldéric\\.atom\\.apmrc" "install" "C:\\Users\\Uldéric\\.atom\\.node-gyp\\.atom\\.apm\\react\\0.8.1\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd D:\TEMP\apm-install-dir-115015-6656-15qzczw
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm

**Comment by bcharbonnier** [comment]
Hello, I am also a Windows user at work, and I got the same issue with Atom 0.170.0, going from atom-react 0.7.8 to 0.8.1

This module 'oniguruma' want to be rebuilt at install time, and this is something super tricky on Windows platform.

It's a real nightmare if you want to be able to node-gyp build native package on Windows. 
You need to install the exact right version of redistribuable visual C++ runtime, with the correct version of python... as I told, it's a nightmare. I managed to setup it once, but never succeeded a second time. 

```
oniguruma@3.0.5 install D:\Temp\apm-install-dir-115015-10592-h6ksdg\node_modules\react\node_modules\oniguruma
> node-gyp rebuild
```

```
npm ERR! oniguruma@3.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@3.0.5 install script.
```

Is there a way to use a pre-built version of this dependency module ? Like socket.io is doing for example ?

**Comment by orktes** [comment]
Thanks for reporting. I just published a new version that tries to use the oniguruma version bundled with atom. Please test if it helps?

**Comment by orktes** [comment]
Just checked that it didn't help :D

**Comment by orktes** [comment]
Removed oniguruma and changed to use LanguageMode to convert the patterns instead. Hopefully atom wont change / break that anytime soon :). New version published.

**Comment by morukutsu** [comment]
I tried the new version on my computer at work and it's working. I will try at home but I guess it will be OK.

Thanks for the quick reply!

**Comment by bcharbonnier** [comment]
It worked like a charm !
thanks for this quick update :+1:

**Comment by orktes** [comment]
Nice! Closing for now! Please reopen if problems persist.
