### ISSUE TITLE
Indentation with ternary operators

### ISSUE THREAD

**Issue by jacobmischka** [orktes/atom-react#198]
Indentation seems to be wrong with ternary operators, it always has one less indentation than I want it to. Or maybe my formatting is out of the norm I guess, but it seems correct.

~~I'm not very good at regex, so I'm not sure if the `decreaseIndentPattern` is the problem, but I'm confused by [line 63 in `atom-react.coffee`](https://github.com/orktes/atom-react/blob/ec2cc5050a9ec7b1138bdd61d1f4e877db8f028c/lib/atom-react.coffee#L63), why is it decrementing the `desiredIndentLevel` no matter what?~~

Oh, I see why it's decrementing, my mistake. It looks like the issue is with `decreaseIndentForNextLinePattern` then. ~~As a workaround I just removed the `</[-_\\.A-Za-z0-9]+>` section for now, but it would be great if the regex would detect if a ternary operator is in use.~~ Okay removing that part isn't a good idea. Here is what I'm currently using: `decreaseIndentForNextLinePattern: "(?x) />\\s*(,|;)?\\s*$ | ^(?!\\s*\\?)\\s*\\S+.*</[-_\\.A-Za-z0-9]+>$"`. Unfortunately, I can't use this as a permanent workaround because of #24.

Behavior:
![peek 2016-09-21 11-27](https://cloud.githubusercontent.com/assets/3939997/18719790/784f526c-7fee-11e6-9f76-364acd6bfa9a.gif)

Debugger:
![screenshot from 2016-09-21 11-22-05](https://cloud.githubusercontent.com/assets/3939997/18719687/0aa3eed0-7fee-11e6-9f2c-9aad4bf8ee19.png)

Thank you! Please let me know if there's anything else I can do to help.

**Comment by lorensr** [comment]
When the `?` is on the next line, it is currently not indented. It would be nice it if it were by default, so that [this indentation](https://www.bennadel.com/blog/3166-how-i-format-the-conditional-ternary-operator-in-coldfusion-and-javascript.htm) would happen:

```js
const size = length > 10
  ? 'large'
  : 'small'
```

Whereas currently after an `auto-indent:apply`, I get:

```js
const size = length > 10
? 'large'
: 'small'
```

Jacob's suggested `(?x) />\\s*(,|;)?\\s*$ | ^(?!\\s*\\?)\\s*\\S+.*</[-_\\.A-Za-z0-9]+>$` messes up my self-closing tags.

**Comment by jacobmischka** [comment]
Huh really? Can you provide an example?

**Comment by lorensr** [comment]
![image](https://cloud.githubusercontent.com/assets/251288/19424689/3b7cc864-93f9-11e6-8513-22a0209bed29.png)

![image](https://cloud.githubusercontent.com/assets/251288/19424692/40a34e76-93f9-11e6-89fb-75884b6e3571.png)

**Comment by jacobmischka** [comment]
As far as I know the only thing my change does is not decrease the indent after a line that starts with `?`, I'm not sure why it's breaking that. That setting is hard coded in two separate places in `atom-react`, I'm not sure if changing it in the settings there will work correctly.

![image](https://cloud.githubusercontent.com/assets/3939997/19424980/94297e68-93f3-11e6-9e89-7fe498425f54.png)

![image](https://cloud.githubusercontent.com/assets/3939997/19425037/eede47bc-93f3-11e6-9508-847a05ef47bf.png)

**Comment by jacobmischka** [comment]
Oh except I didn't notice 7b2d132339f6366238e44df46da0b341830f4bfe, changing it in the settings probably does work correctly after that. I'm not sure why it's breaking that case for you then.

**Comment by jacobmischka** [comment]
Closing because I no longer have this problem with recent update
