### ISSUE TITLE
Atom hard crash after hitting enter twice in JSX file

### ISSUE THREAD

**Issue by dmnd** [orktes/atom-react#21]
1. Create new file
2. Set grammar to JSX
3. Hit enter
4. Hit enter again
5. Atom crashes with no stacktrace

This doesn't repro in any other grammar and obviously doesn't repro in safe mode since that doesn't have JSX

**Comment by orktes** [comment]
https://github.com/orktes/atom-react/commit/320b5d8d2b694403025879c37588b3b284c8073f

crash caused when providing empty string to oniguruma

New version published. Thanks again for reporting!

**Comment by dmnd** [comment]
Thanks for the quick fix!

/cc @zgotsch
