### ISSUE TITLE
Install react package in atom..

### ISSUE THREAD

**Issue by Oblik-Design** [orktes/atom-react#219]
I need this, what do I do ? 

Installing “react@0.16.2” failed.Hide output…

npm WARN addRemoteGit git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote /Users/axez/.atom/.apm/_git-remotes/git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/axez/.atom/.apm/_git-remotes/_templates --mirror https://github.com/millermedeiros/rocambole.git /Users/axez/.atom/.apm/_git-remotes/git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/axez/.atom/.apm/.apmrc" "--userconfig" "/Users/axez/.atom/.apmrc" "install" "/private/var/folders/c6/l09zsrd57txd06_sw3p6z1dw0000gp/T/d-11702-715-y6446c/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/axez/.atom/.apm/_git-remotes/_templates --mirror https://github.com/millermedeiros/rocambole.git /Users/axez/.atom/.apm/_git-remotes/git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/c6/l09zsrd57txd06_sw3p6z1dw0000gp/T/apm-install-dir-11702-715-tecb67/npm-debug.log

**Comment by leftfieldhero** [comment]
Same issue with Atom version 1.13.0.

**Comment by Oblik-Design** [comment]
just install the xcode command line tools.

**Comment by Doufeni** [comment]
I have the same problem and i don't understand the solution.
