### ISSUE TITLE
Reopening of #108 - Use spaces for indent (instead of tabs)

### ISSUE THREAD

**Issue by rsshilli** [orktes/atom-react#223]
This issue isn't fixed.  It seems atom react insists on using tabs, regardless of my Atom settings.  Super annoying. 

Vaguely Quoting @traviskroberts from #108 :
I have "Tab type" set to "soft" with a "Tab Length" of 2 in the Atom settings and this package is overwriting this and forcing a tab size of 4.

**Comment by orktes** [comment]
tab vs space is controlled trough atom settings. i.e this plugin wont affect your tab length. this settings can either be controlled on a global level or in the settings on a specific grammar (language plugin).

**Comment by rsshilli** [comment]
Yup.  I'm sorry.  My keymap was accidentally bound to the wrong thing.  I can confirm that once it was bound to the right "Editor: Indent" then everything started working better.  Sorry about that.
