### ISSUE TITLE
Not highlighting as of 0.9.0

### ISSUE THREAD

**Issue by caseywebdev** [orktes/atom-react#25]
One of the changes between `0.8.8` and `0.9.0` has caused highlighting to stop working for me and `0.9.3` does not work either. I'm using `atom@0.175.0`. I've switched back to `0.8.8` for now. Any thoughts on how to troubleshoot the issue I'm having with the new version?

**Comment by orktes** [comment]
Hi!

Biggest change that was made was the fact that we now extend the default source.js highlighting for normal JS highlighting. 

Have you restarted your editor? Are you getting any highlighting (js code) or just not the JSX parts? What OS? What is you file extension? You have the right grammar set / you see Javascript (JSX) in the bottom bar?

![screenshot 2015-01-26 10 02 29](https://cloud.githubusercontent.com/assets/606347/5896712/af94616e-a542-11e4-9dce-a4222aa48a59.png)

**Comment by caseywebdev** [comment]
Ah that was the issue. I had disabled the JavaScript grammar because I was using the JSX grammar for .js/.es6/.jsx. I've re-enabled it and everything is working. Thanks!

**Comment by orktes** [comment]
Nice to know! I should probably add some sort of a error/message bar for displaying information about this kind of situations :)
