### ISSUE TITLE
Installing “react@0.18.0” failed.

### ISSUE THREAD

**Issue by AmjadRathod** [orktes/atom-react#272]
I will try to install react but atom say

Failed to install react because Git was not found.

The react package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

but i have already installed git and i will created lots off repo in git.

**Comment by noudadrichem** [comment]
+1 on this. Actually every update you pushed so far made me uninstall and reinstall this package again. Not that I care, but might be something to look at. Could also be on my end but this is the only package where this problem occurs.

So far so good, great package. Love it!

Sincerely

**Comment by AmjadRathod** [comment]
Thanks for your help.
