### ISSUE TITLE
How can I use Autocomplete and Automatic closing tag?

### ISSUE THREAD

**Issue by helloworld-hellohyeon** [orktes/atom-react#296]
I can't find keybindings of these functions. How can I use these?

**Comment by TranQuocViet** [comment]
i facing same issue, cant auto close tag white orther features working fine

**Comment by santosh07bec** [comment]
I am also facing this issue. Any update?

**Comment by helloworld-hellohyeon** [comment]
Sorry but I couldn't find the solution :( I'm using VScode instead.

**Comment by tomascsantos** [comment]
Still doesn't seem to work?

**Comment by helloworld-hellohyeon** [comment]
Sorry for disappointing reply but the answer is not yet. I'm using VSCode editor and extensions instead.
