### ISSUE TITLE
Remove source selected when "shift+tab" pressed

### ISSUE THREAD

**Issue by lbonomo** [orktes/atom-react#303]
When I press "shift+tab" several times, the source selected was disappear and do not work undo "ctrl+z"

**Comment by OliverBalfour** [comment]
I'm having the same issue sporadically with `atom-react`, it only seems to happen when multiple lines are selected. Also, it looks like this has been an issue since Jan 2018 - see [this issue](https://github.com/atom/atom/issues/16470).
