### ISSUE TITLE
Feature Request: Auto-close JSX tags when typing `</`

### ISSUE THREAD

**Issue by mehcode** [orktes/atom-react#32]
There are packages for atom that auto-close HTML / XML tags when typing `</`. This package sounds like a  good place for such a feature for JSX.

**Comment by orktes** [comment]
Hi! Thanks for your feedback. Adding this is in the plans among other emmet type features. I'll most likely get started during the weekend.

**Comment by nextriot** [comment]
Would love to see this in place! Thanks for the great plugin.

**Comment by orktes** [comment]
Hi! Had some extra time today so I decided to move forward with this feature.

![taghandling](https://cloud.githubusercontent.com/assets/606347/6997161/28412172-dbb9-11e4-9719-2d58b0b79b3f.gif)

**Comment by orktes** [comment]
So instead of auto-closing closing tags I decided to take similar approach that atom takes with curly braces. Everyone okay with it?

**Comment by orktes** [comment]
Just released a new version that contains it. Closing for now.

**Comment by maxguzenski** [comment]
It is not working with coffescript (.cjsx files)...

**Comment by benrlodge** [comment]
@maxguzenski have you found a package for `cjsx`? My googling is coming up short

**Comment by maxguzenski** [comment]
@benrlodge  I dont remember, I've ported everting to es6
