### ISSUE TITLE
Feature Request: Look for a syntax indicator in .js files

### ISSUE THREAD

**Issue by mehcode** [orktes/atom-react#33]
Something like: 

```js
// -*- syntax: jsx -*-
```

**Comment by orktes** [comment]
https://github.com/orktes/atom-react/commit/c970cebbf5199e5ed4c9c0cf191c74256c134055 just did initial functionality to detect JSX based on if require('react') is defined in the code. Before next release I'll change the pattern to be configurable from the settings. i.e you can change is to detect anything that fits your needs.

**Comment by mehcode** [comment]
@orktes Ah. That would work. Do you think you could make the default look for ES6 style imports of react as well? Something like `import.*from.*"react"`.

**Comment by orktes** [comment]
Good idea! I'll add it before next release.

**Comment by nick** [comment]
Cool looking forward to this :+1:
