### ISSUE TITLE
REformat not working

### ISSUE THREAD

**Issue by luisrudge** [orktes/atom-react#34]
![atom-react](https://cloud.githubusercontent.com/assets/941075/6092412/ff1c0030-aec4-11e4-821e-422ad6d4b0f1.gif)

**Comment by orktes** [comment]
Hi! As the reformating parses the code the selection needs to contain valid
JavaScript+JSX but your example contains invalid code/tokens. I could add
error messages for situations like this for future versions.

**Comment by Trudko** [comment]
Hi @orktes  , I tried to format simple JSX but if it works depended on cursor position:

![react](https://cloud.githubusercontent.com/assets/3289225/6514181/add45d78-c380-11e4-9616-33ea449f7699.gif)

**Comment by orktes** [comment]
Formating is done for selections like other atom edit features. I.e you
have to select the part you want to reformat. Also formating only affects
JSX code http://facebook.github.io/jsx/ hence "reformat jsx". Normal
JavaScript is only reindended.

On Thursday, March 5, 2015, Trudko <notifications@github.com> wrote:

> Hi @orktes <https://github.com/orktes> , I tried to format simple JSX but
> if it works depended on cursor position:
>
> [image: react]
> <https://cloud.githubusercontent.com/assets/3289225/6514181/add45d78-c380-11e4-9616-33ea449f7699.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/34#issuecomment-77447657>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by orktes** [comment]
Video demo of the feature usage
http://orktes.github.io/atom-react/#jsx-reformatting

On Thursday, March 5, 2015, Jaakko Lukkari <jaakko.lukkari@gmail.com> wrote:

> Formating is done for selections like other atom edit features. I.e you
> have to select the part you want to reformat. Also formating only affects
> JSX code http://facebook.github.io/jsx/ hence "reformat jsx". Normal
> JavaScript is only reindended.
>
> On Thursday, March 5, 2015, Trudko <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hi @orktes <https://github.com/orktes> , I tried to format simple JSX
>> but if it works depended on cursor position:
>>
>> [image: react]
>> <https://cloud.githubusercontent.com/assets/3289225/6514181/add45d78-c380-11e4-9616-33ea449f7699.gif>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/orktes/atom-react/issues/34#issuecomment-77447657>.
>>
>
>
> --
> Ystävällisin terveisin,
> Jaakko Lukkari
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari
