### ISSUE TITLE
Feature request: CJSX (CoffeeScript) Snippets

### ISSUE THREAD

**Issue by burtyish** [orktes/atom-react#35]
I just installed Atom to see if there's better support for .cjsx files (coming from Sublime with [sublime-react](https://github.com/reactjs/sublime-react)) and I'm very impressed by the work you've done here.
Oddly, though, I can't get snippets to work.
For example, I type `rcc`<kbd>tab</kbd> and ... nothing.
I'm I doing something wrong?

**Comment by orktes** [comment]
Hi! 

Thanks for the kind words! Currently CJSX support only contains highlighting support. I dont personally use CJSX and the syntax highlighting part was a contribution. I could though port the current javascript snippets to coffeescript and see if I can get the automatic indentation support working on CJSX side as well. Reformatting support might take more work as I haven't yet taken a look on how the CJSX compiler works.

**Comment by orktes** [comment]
@rylanc any change you might be interested in implementing these or if you by change happen to already have the snippets converted?
