### ISSUE TITLE
Feature Request: Tab Length only in JSX context

### ISSUE THREAD

**Issue by nick** [orktes/atom-react#38]
My regular JS files have a tab length of 4 spaces, but I'd like the JSX parts to have 2 spaces. Is there any way to have Tab Length preference only apply when in a JSX context? I'll have a go at implementing it myself if you have any pointers.

**Comment by orktes** [comment]
Hi!

I'm not a huge fan of this sort of approach as a feature for this plugin but you could be able to implement this by using the scoped settings. http://blog.atom.io/2014/10/31/language-scoped-config.html
