### ISSUE TITLE
All .js files open with jsx grammar

### ISSUE THREAD

**Issue by radum** [orktes/atom-react#39]
All my .js files open with jsx grammar by default.

Not sure if this is by design but it breaks things for me and I think we should leave .js as they are unless you detect react components inside the source.

**Comment by orktes** [comment]
Hi! It's originally by design but I think with the new detection functionality we can remove .js from the extensions list.

**Comment by radum** [comment]
Awesome, thanks.

**Comment by breathe** [comment]
atom-react isn't being used for my .js files ...  Instead its using the builtin babel functionality.  It seems like atom-react's functionality is better(?) ...

Is there an up-to-date best-practice on which extension to use for folks using react, webpack, and babel?
