### ISSUE TITLE
classSet as part of React with addons is deprecated in v0.13

### ISSUE THREAD

**Issue by jokeyrhyme** [orktes/atom-react#40]
http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html#react-with-add-ons
> `React.addons.classSet` is now deprecated. This functionality can be replaced with several freely available modules. [classnames](https://www.npmjs.com/package/classnames) is one such module.

This may affect the `cs` snippet thing you offer.

**Comment by orktes** [comment]
Thanks for informing!
