### ISSUE TITLE
Incorrect Syntax highlight of Namespaced components

### ISSUE THREAD

**Issue by ntotten** [orktes/atom-react#42]
React now allows using namespaced components like:

```
var Foo = require('foo');
```

```
<Foo.MyComponent>
   <p>Something</p>
</Foo>MyComponent>
```

Currently the highlighting shows the portion after the period (In this example `PageHeader` and `ModalTrigger`) in the same color as an attribute, where as it should be the same color as an element tag.

![screenshot 2015-03-06 15 18 58](https://cloud.githubusercontent.com/assets/282782/6538213/2833860a-c414-11e4-8356-87d4fb2f213f.png)

**Comment by orktes** [comment]
Thanks for informing!

**Comment by orktes** [comment]
New version published.
