### ISSUE TITLE
Is there any options for replacing "require" to "import"? 

### ISSUE THREAD

**Issue by TanTan-TT** [orktes/atom-react#47]
We use "import React from 'react'" for our code. Could you support it?

**Comment by orktes** [comment]
Hi! Just to clarify. You are talking about the component skeleton snippet?

**Comment by TanTan-TT** [comment]
Yes.

**Comment by orktes** [comment]
Sorry for the delay! I can add it but you can also add it as a custom user defined snippet to you atom settings.

**Comment by TanTan-TT** [comment]
Ok, thx, I will do this
