### ISSUE TITLE
Feature Request: Autocomplete+ provider support for as you type suggestions

### ISSUE THREAD

**Issue by JamesReate** [orktes/atom-react#49]
https://atom.io/packages/autocomplete-plus

Their autocomplete as you type works pretty well and it would be nice to plug in as a provider to take advantage of that. Not sure if it would mean re-inventing the way the language service is built.

**Comment by orktes** [comment]
Hi! This plugin should work just fine with autocomplete-plus. I.e standard tags and attributes should appear in autocompletion menu along with normal JS symbols.
