### ISSUE TITLE
unable to install Atom

### ISSUE THREAD

**Issue by agile116** [orktes/atom-react#51]
Hi, I'm getting the following error. Please suggest how to solve it. Thanks.
Installing “react@0.11.2” failed.Hide output…

npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/millermedeiros/rocambole.git) 
npm ERR! git clone https://github.com/millermedeiros/rocambole.git Cloning into bare repository 'C:\Users\XXXXXX\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-df2b88ba'...
npm ERR! git clone https://github.com/millermedeiros/rocambole.git fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Failed connect to github.com:1080; No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\project\\software\\Atom\\resources\\app\\apm\\bin\\\\node.exe" "C:\\project\\software\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\XXXXXX\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\XXXXXX\\.atom\\.apmrc" "install" "C:\\Users\\XXXXXX\\AppData\\Local\\Temp\\d-11538-5936-1mjqice\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\XXXXX\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-df2b88ba'...
npm ERR! fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Failed connect to github.com:1080; No error
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by orktes** [comment]
Hi. Based on "unable to access '
https://github.com/millermedeiros/rocambole.git/': Failed connect to
github.com:1080;" it seems that you might have had temporary problems
accessing github. Please try again.

2015-04-08 5:42 GMT+03:00 agile116 <notifications@github.com>:

> Hi, I'm getting the following error. Please suggest how to solve it.
> Thanks.
> Installing “react@0.11.2” failed.Hide output…
>
> npm WARN git config --get remote.origin.url returned wrong result (
> https://github.com/millermedeiros/rocambole.git)
> npm ERR! git clone https://github.com/millermedeiros/rocambole.git
> Cloning into bare repository
> 'C:\Users\XXXXXX.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-df2b88ba'...
> npm ERR! git clone https://github.com/millermedeiros/rocambole.git fatal:
> unable to access 'https://github.com/millermedeiros/rocambole.git/':
> Failed connect to github.com:1080; No error
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\project\software\Atom\resources\app\apm\bin\\node.exe"
> "C:\project\software\Atom\resources\app\apm\node_modules\npm\bin\npm-cli.js"
> "--globalconfig" "C:\Users\XXXXXX\.atom\.apm\.apmrc" "--userconfig"
> "C:\Users\XXXXXX\.atom\.apmrc" "install"
> "C:\Users\XXXXXX\AppData\Local\Temp\d-11538-5936-1mjqice\package.tgz"
> "--target=0.22.0" "--arch=ia32"
> npm ERR! node v0.10.35
> npm ERR! npm v2.5.1
> npm ERR! code 128
>
> npm ERR! Command failed: Cloning into bare repository
> 'C:\Users\XXXXX.atom.apm_git-remotes\https-github-com-millermedeiros-rocambole-git-df2b88ba'...
> npm ERR! fatal: unable to access '
> https://github.com/millermedeiros/rocambole.git/': Failed connect to
> github.com:1080; No error
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR! http://github.com/npm/npm/issues
> <https://github.com/npm/npm/issues>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/51>.
>



-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by agile116** [comment]
Hi, still the same issue.
