### ISSUE TITLE
Inserting ">" for arrow functions in a JSX prop inserts a closing tag

### ISSUE THREAD

**Issue by ide** [orktes/atom-react#52]
With atom-react 11.2, if I have a component with an arrow function in a prop, typing ">" inserts a closing tag.

```js
<Example
  onClick={(event) =>}  // As soon as I type ">" it inserts </Example>
/>
```

**Comment by orktes** [comment]
Oh didn't forgot arrow functions totally when I did the last release. I'll
push a fix to that in an hour. Thanks for informing!

**Comment by ide** [comment]
Super fast! Thank you!

**Comment by orktes** [comment]
Hi! Should now be fixed. If any other issues come up feel free to reopen. Apologies for the inconvenience.

**Comment by orktes** [comment]
Just published a new version also!
