### ISSUE TITLE
Add snippets for ES6 classes

### ISSUE THREAD

**Issue by stremlenye** [orktes/atom-react#55]
Does anybody thought about it?
I know that snippets could be added to atom by the bare hands but would be great to have them ready out of the box.

**Comment by magalhas** [comment]
:+1:

**Comment by magalhas** [comment]
+1

**Comment by skitoo** [comment]
+1

**Comment by framerate** [comment]
I would very much be interested in this. Perhaps @orktes wants to get us started and we can do a PR?

**Comment by orktes** [comment]
https://github.com/orktes/atom-react/pull/68 Merged! Thanks @stremlenye

**Comment by framerate** [comment]
Did this get pushed @orktes? I saw a new version but don't see the option

**Comment by framerate** [comment]
I think this can be closed now!

**Comment by stremlenye** [comment]
:+1:
