### ISSUE TITLE
Error: missing / (unclosed regex)

### ISSUE THREAD

**Issue by ScreenDriver** [orktes/atom-react#59]
I use CoffeeScript with the React library. So I use CJSX files. Unfortunately I get following error:

![screenshot](https://cloud.githubusercontent.com/assets/149248/7468060/0f5f99ba-f304-11e4-97d4-30638bde9fb9.png)

**Comment by orktes** [comment]
Hi!

That is output from the coffeescript linter you are using. You need to
request cjsx support from their side to get rid of the warning/error.

**Comment by ScreenDriver** [comment]
Oh, I am sorry. This was the wrong GitHub project. I opened the right one in another browser tab :flushed:
