### ISSUE TITLE
Put tag auto-completion behind a settings flag

### ISSUE THREAD

**Issue by numso** [orktes/atom-react#60]
When typing an array in flow, it's written as: `var myData: Array<Thing> = ...`. This new feature causes the code to autocomplete to `var myData: Array<Thing></Thing> = ...`. Not terrible, easy enough to delete the closing tag. Still, it'd be nice to have a setting to turn it off.

**Comment by orktes** [comment]
Hi!

It's already there :) Sorry about the vague naming and missing descriptions (Description will be added in the next release).

![screenshot 2015-05-11 20 06 23](https://cloud.githubusercontent.com/assets/606347/7570491/48b8fae8-f819-11e4-9691-9199348a0a2e.png)

**Comment by numso** [comment]
Ah, I was still a version or two behind. My bad. Thanks so much!
