### ISSUE TITLE
Falsely detects CoffeeScript files (.coffee) as CoffeeScript (JSX)

### ISSUE THREAD

**Issue by tylerFowler** [orktes/atom-react#62]
I just noticed this starting yesterday (with the latest version of Atom .200 and the latest version of this package 0.11.8), but the lang autodetect is marking my (very regular) CoffeeScript files as CJSX files. Frankly I think the only file extension that should be marked are `.cjsx` files.

**Comment by orktes** [comment]
Hi! Sorry for the delay. Fixed in the next release!

**Comment by SPSpwetter** [comment]
I have the reverse problem. All of our coffee script files are essentially CJSX, and the file suffixes aren't editable from settings.

**Comment by orktes** [comment]
Hi! As the plugin already has a "enable for all js files" -setting in the preferences there is no reason for not having one for coffee as well. I'll add this to the next update.

**Comment by SPSpwetter** [comment]
Awesome, thanks
