### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by jrodl3r** [orktes/atom-react#63]
Will add screenshots later, but I've been having serious memory consumption issues with Atom for a few weeks now, and I'm almost positive that this package might have something to do with it.

Basically, When working with larger files (600-1000 lines) the performance drops, scrolling starts to jank and Activity Monitor shows Atom using up between 1GB-1.6GB of memory.

Just a heads-up for now, still testing without this package enabled. Much appreciated if you have any pointers or advice on the matter.

**Comment by orktes** [comment]
Hi,

The plugin is not attaching to any scroll events and I therefore find it
odd that it would have impact on the scrolling performance.

**Comment by jrodl3r** [comment]
Just to be 100% clear, I'm not entirely sure this package is causing it. However, anything chewing up that amount of memory is bound to have side effects like choppy scrolling.

I really wanted to see if anyone else is experiencing memory issues with this package in particular. Anything to help narrow down the possible causes.

Thx

**Comment by orktes** [comment]
Which features have you used from the plugin? I cant think of any features that would chew up memory and for example the syntax highlighting is done by atom itself. How does your heap snapshot look like?

**Comment by orktes** [comment]
For me 94% of the retained heap is going to DOM elements with or without the react plugin.

**Comment by orktes** [comment]
AtomReact object seems to retain something like 10kt.

**Comment by orktes** [comment]
Opened and closed a 3000 lines file about 15 times and snapshot looks the same with or without this plugin. I.e. lots of DisplayBuffers retained even when there are no editor windows open. So it seems to be the same/similar findings than in https://github.com/atom/atom/issues/5721.

Also
https://github.com/atom/atom/issues/1827

closing for now.
