### ISSUE TITLE
Syntax Highlighting works only for the JSX part of the code

### ISSUE THREAD

**Issue by despairblue** [orktes/atom-react#64]
![screenshot from 2015-06-02 21-02-52](https://cloud.githubusercontent.com/assets/927609/7944421/c7bcb8fe-096a-11e5-8a06-0598584c06fe.png)

Is this intended behavior? Since in the show case videos also the javascript part is highlighted.

**Comment by orktes** [comment]
Hi!

The plugins tries to import the .js grammar you have enabled for atom. I.e
you need to have language-javascript plugin or equivalent enabled (Not
selected but enabled).

On Tuesday, June 2, 2015, Danny Arnold <notifications@github.com> wrote:

> [image: screenshot from 2015-06-02 21-02-52]
> <https://cloud.githubusercontent.com/assets/927609/7944421/c7bcb8fe-096a-11e5-8a06-0598584c06fe.png>
>
> Is this intended behavior? Since in the show case videos also the
> javascript part is highlighted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/64>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by despairblue** [comment]
Ok, after reloading Atom everything works.

Thanks for this amazing package :+1:

**Comment by orktes** [comment]
Glad that it helped! Thank you for kind words!
