### ISSUE TITLE
Apply to js files by default

### ISSUE THREAD

**Issue by LinusU** [orktes/atom-react#66]
I would like to have an option to always use `JavaScript (JSX)` for all of my javascript files. Since I use `.js` as the file extension I have to manually change it every time I create a new file :S

**Comment by demohi** [comment]
+1

**Comment by orktes** [comment]
Hi,

I could add this as an opt-in setting?

**Comment by LinusU** [comment]
That would be very good :+1:

**Comment by orktes** [comment]
Fixed. Sorry for the delay. Will publish a new release that includes this today.

**Comment by LinusU** [comment]
Thanks! I can't find it in my settings thought :( am I missing something?

**Comment by demohi** [comment]
:+1:
