### ISSUE TITLE
Not loading up language support when using React with addons

### ISSUE THREAD

**Issue by mariopeixoto** [orktes/atom-react#70]
Package is not loading up language support when using React with addons as bellow:

<code>
import React from 'react/addons';
</code>

or 

<code>
var React = require('react/addons');
</code>

**Comment by mariopeixoto** [comment]
Fixed on pull request #71.

As a workaround, one can go to the package settings in atom and change the React File Pattern property to:
<code>
/((require\(['"]react(?:(-native|\/addons))?['"]\)))|(import\s+\w+\s+from\s+['"]react(?:(-native|\/addons))?['"])/
</code>

**Comment by orktes** [comment]
PR merged! Thanks!
