### ISSUE TITLE
How to disable сlosing tag auto-completion?

### ISSUE THREAD

**Issue by dkiyatkin** [orktes/atom-react#76]

**Comment by orktes** [comment]
Hi,

https://github.com/orktes/atom-react/issues/60

On Tuesday, June 30, 2015, Dmitriy Kiyatkin <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/76>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by dkiyatkin** [comment]
Thx! This works!
