### ISSUE TITLE
Doesn't seem to recognize files that import React and PropTypes

### ISSUE THREAD

**Issue by qimingweng** [orktes/atom-react#79]
The package highlights files that start with `import React from 'react'`, but does not highlight `import React, {PropTypes} from 'react'`

**Comment by qimingweng** [comment]
My current solution is to change the "Detect React File Pattern" to something like 

```javascript
/(import.*from .react.|require\(.react.*\))/
```

**Comment by orktes** [comment]
Should be fixed! Doing a release asap.
