### ISSUE TITLE
HTML Auto Close double-closing

### ISSUE THREAD

**Issue by gseyffert** [orktes/atom-react#82]
For instance, auto-closing an < img > tag will result in < img >< /img >< /img >. Restarting Atom can solve this issue, toggling "Disable Auto-Close" in package settings does not.

**Comment by davezuko** [comment]
I've been experiencing this as well, though it's so random that it's hard to pinpoint a cause. Doesn't seem to be tag-specific.

**Comment by orktes** [comment]
I'll take a look tomorrow. Thanks for reporting!

On Monday, July 13, 2015, David Zukowski <notifications@github.com> wrote:

> I've been experiencing this as well, though it's so random that it's hard
> to pinpoint a cause. Doesn't seem to be tag-specific.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/82#issuecomment-120989663>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by gseyffert** [comment]
Sorry, realized my comment wasn't displaying properly. Added some spaces to prevent the tags from being interpreted as markdown.

**Comment by orktes** [comment]
Hi! I'm ATM looking into this. What versions are you using? There has been similar issues in the past but those should be resolved. https://github.com/orktes/atom-react/issues/54

**Comment by gseyffert** [comment]
I have  0.12.4 installed

**Comment by davezuko** [comment]
On Atom `1.0.2` with atom-react at `0.12.4`

**Comment by despairblue** [comment]
Also happing with atom-react 0.12.6.

## Versions

* **Atom:**       1.0.11
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.5
* **Misc**
    * apm  1.0.4
    * npm  2.13.3
    * node 0.10.40
    * python 2.7.10
    * git 2.3.2

**Comment by billyjacoby** [comment]
this is still an issue for me, on macOS.
