### ISSUE TITLE
Breaks array indentation of `language-babel` package

### ISSUE THREAD

**Issue by aaronjensen** [orktes/atom-react#86]
If I have `language-babel` installed and this package, when using the "Babel ES6 Javascript" grammar, array indentation does not work properly.

See https://github.com/gandm/language-babel/issues/32

Currently it looks like this (a regular JS file w/ the "Babel ES6 Javascript" grammar selected):

```js
  mixins: [
  Stores.CurrentUser.mixin,
  Stores.CoachParticipants.mixin,
  Stores.Errors.mixin,
  Stores.LastViewed.mixin,
  Stores.ParticipantConversations.mixin,
  Stores.ParticipantGoal.mixin,
  Stores.ParticipantSuggestions.mixin,
  Stores.PendingUpdate.mixin,
  RouteHandlerKey
  ],
```

I expect it to look like this (how https://github.com/atom/language-javascript indents them):

```js
  mixins: [
    Stores.CurrentUser.mixin,
    Stores.CoachParticipants.mixin,
    Stores.Errors.mixin,
    Stores.LastViewed.mixin,
    Stores.ParticipantConversations.mixin,
    Stores.ParticipantGoal.mixin,
    Stores.ParticipantSuggestions.mixin,
    Stores.PendingUpdate.mixin,
    RouteHandlerKey
  ],
```

**Comment by orktes** [comment]
Thanks for reporting! I'll try to see what the problem is.

On Friday, July 24, 2015, Aaron Jensen <notifications@github.com> wrote:

> If I have language-babel installed and this package, when using the
> "Babel ES6 Javascript" grammar, array indentation does not work properly.
>
> See gandm/language-babel#32
> <https://github.com/gandm/language-babel/issues/32>
>
> Currently it looks like this (a regular JS file w/ the "Babel ES6
> Javascript" grammar selected):
>
>   mixins: [
>   Stores.CurrentUser.mixin,
>   Stores.CoachParticipants.mixin,
>   Stores.Errors.mixin,
>   Stores.LastViewed.mixin,
>   Stores.ParticipantConversations.mixin,
>   Stores.ParticipantGoal.mixin,
>   Stores.ParticipantSuggestions.mixin,
>   Stores.PendingUpdate.mixin,
>   RouteHandlerKey
>   ],
>
> I expect it to look like this (how
> https://github.com/atom/language-javascript indents them):
>
>   mixins: [
>     Stores.CurrentUser.mixin,
>     Stores.CoachParticipants.mixin,
>     Stores.Errors.mixin,
>     Stores.LastViewed.mixin,
>     Stores.ParticipantConversations.mixin,
>     Stores.ParticipantGoal.mixin,
>     Stores.ParticipantSuggestions.mixin,
>     Stores.PendingUpdate.mixin,
>     RouteHandlerKey
>   ],
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/86>.
>


-- 
Ystävällisin terveisin,
Jaakko Lukkari

**Comment by orktes** [comment]
should be fixed now. react@v0.12.6 published.

**Comment by aaronjensen** [comment]
Thanks, confirmed.
