### ISSUE TITLE
I cannot get the reformatting to work at all. 

### ISSUE THREAD

**Issue by dijs** [orktes/atom-react#90]
I am using es6 with react, although each time I mess up the code and try to "reformat" with this plugin. The code doesn't change. 

Is there anyway I can debug this plugin?

**Comment by orktes** [comment]
seems to be a problem with rocambole trying to get this fixed asap.

**Comment by dijs** [comment]
Thank you

**Comment by orktes** [comment]
v0.12.8 published. Should fix the issue! thanks for reporting!

**Comment by orktes** [comment]
ps. before https://github.com/orktes/atom-react/issues/72 is done the reformatting might have limitations.

**Comment by dijs** [comment]
Okay. Thanks for your work.
