### ISSUE TITLE
Multiple Cursor Autocomplete Not Working Properly

### ISSUE THREAD

**Issue by ccmeyers** [orktes/atom-react#93]
Say I have two div's:
```
  <div>
 
  </div>
  <div>

  </div>
```
If I use multiple cursors to try to put a p tag in each at the same time, autocomplete gives me this:
```
  <div>
    <p>></p>
  </div>
  <div>
    <p</p>
  </div>
```
atom version: 1.0.11
atom-react version: 0.12.8
OS X Yosemite version: 10.10.5

**Comment by orktes** [comment]
Hi! Thanks for reporting! I planning to fix this similarly how the default bracket matcher works. I.e. I wont even try to auto close if multiple cursors are present. Lets see if I have time to improve it in the future.

**Comment by orktes** [comment]
version v0.12.9 published with a fix for this.
