### ISSUE TITLE
Enable JSX syntax highlighting for files with .es6 extension

### ISSUE THREAD

**Issue by Valve** [orktes/atom-react#94]
I couldn't find a place to ask a question for this plugin, but the title says it: I have a file with JSX that has .es6 extension (which I cannot change). How do I enable syntax highlighting for these types of files?

**Comment by orktes** [comment]
Hi you can select the grammar from the bottom left ![screenshot 2015-07-14 13 17 35](https://cloud.githubusercontent.com/assets/606347/8671079/cda781c8-2a2a-11e5-90f4-e5419b543690.png)

**Comment by orktes** [comment]
Closing. Feel free to open if you need more info.

**Comment by Valve** [comment]
@orktes oh, I was dumb, thanks!
