### ISSUE TITLE
Flux Store Snippet

### ISSUE THREAD

**Issue by adamellsworth** [orktes/atom-react#97]
I've put together a quick Flux Store snippet: (assumes App dispatcher is located at `../../` from Store)

    "React: flux store skeleton":
        prefix: "fxs"
        body: "var Dispatcher = require('../../ApplicationDispatcher.js');\nvar EventEmitter = require('events').EventEmitter;\nvar assign = require('object-assign');\n\nvar ${1} = assign({}, EventEmitter.prototype, {\n\n\n\n\temitChange: function() {\n\t\tthis.emit('change');\n\t},\n\n\taddChangeListener: function(callback) {\n\t\tthis.on('change', callback);\n\t},\n\n\tremoveChangeListener: function(callback) {\n\t\tthis.removeListener('change', callback);\n\t}\n});\n\n${1}.dispatchToken = ApplicationDispatcher.register(function(payload) {\n\tvar action = payload.action, data = payload.action.data;\n});\n\nmodule.exports = ${1};"

**Comment by orktes** [comment]
Hi! 

I try to keep this project clean of any non-react related stuff and tough Flux is directly related to React I still consider it to be out of the scope of this project. Also I think https://atom.io/packages/react-snippets might already have some flux snippets.
