### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by dsernst** [orktes/atom-react#99]
Any plans to add an official changelog?

**Comment by orktes** [comment]
Why not! I'll start maintaining one now so we'll have one in the future.

**Comment by dsernst** [comment]
:+1: thanks for the quick reply

On Wednesday, September 30, 2015, Jaakko Lukkari <notifications@github.com>
wrote:

> Closed #99 <https://github.com/orktes/atom-react/issues/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orktes/atom-react/issues/99#event-422982943>.
>


-- 
--
David Ernst
